name: Reusable Workflow

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: ${{ inputs.language == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies Node.js project
        if: ${{ inputs.language == 'node' }}
        run: |
          cd nodejs
          npm install

      - name: Set up PHP
        if: ${{ inputs.language == 'php' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies and build PHP project
        if: ${{ inputs.language == 'php' }}
        run: |
          cd php
          composer install
          # Comando para compilar ou gerar artefato, se necessário

      - name: Set up Java
        if: ${{ inputs.language == 'java' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Java project
        if: ${{ inputs.language == 'java' }}
        run: |
          cd java
          mvn clean package

      - name: Set up .NET
        if: ${{ inputs.language == 'aspnet' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9'

      - name: Build .NET project
        if: ${{ inputs.language == 'aspnet' }}
        run: |
          cd aspnet
          cd HelloWorldApi
          dotnet restore
          dotnet build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.language }}-build-artifact
          path: |
            node/dist
            php/build
            java/target/*.jar
            aspnet/HelloWorldApi/bin